// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMfMkayZI_VnYmFMeU0g_56u2dXDN32c',
    appId: '1:875375972752:web:02f3726e7d359c6a63e315',
    messagingSenderId: '875375972752',
    projectId: 'chat-app-8e984',
    authDomain: 'chat-app-8e984.firebaseapp.com',
    storageBucket: 'chat-app-8e984.appspot.com',
    measurementId: 'G-MJPV78H25T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtw5kk9Tyd3h6mSFZ1rsGl_8jF1ZzIx-g',
    appId: '1:875375972752:android:d184cdac09f4c56763e315',
    messagingSenderId: '875375972752',
    projectId: 'chat-app-8e984',
    storageBucket: 'chat-app-8e984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbDnUYaOYYmUlbT29sMatIERNx16HGI-c',
    appId: '1:875375972752:ios:754ab98bd0fb954863e315',
    messagingSenderId: '875375972752',
    projectId: 'chat-app-8e984',
    storageBucket: 'chat-app-8e984.appspot.com',
    iosBundleId: 'com.mostafa.chatapp',
  );
}
